import Head from "next/head";
import { StarRating } from "components/StarRating";
import { TextArea } from "components/TextArea";
import { TextInput } from "components/TextInput";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Submit feedback</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Submit your feedback</h1>
        <form className={styles.form}>
          <div>
            <div className={styles.inputWrapper}>
              <TextInput label="Full name" id="input-full-name" />
            </div>
            <div className={styles.inputWrapper}>
              <TextInput label="Email" id="input-email" />
            </div>
            <StarRating />
          </div>
          <TextArea label="Comments" id="input-comments" />
        </form>
      </main>
    </>
  );
}
