import { Bar, BarChart, ResponsiveContainer, XAxis, YAxis } from "recharts";
import { Comment, LatestComments } from "components/LatestComments";

import Head from "next/head";
import { Page } from "components/Page";
import { TextLink } from "components/TextLink";
import dynamic from "next/dynamic";
import styles from "../styles/Submitted.module.scss";
import { useLocalStorage } from "hooks/useLocalStorage";

const LazyLoadedLatestComments = dynamic(
  () => import("components/LatestComments"),
  {
    ssr: false,
  }
);

export default function Submitted() {
  const [feedback] = useLocalStorage<Comment[]>("feedback", []);

  const ratingDistribution = feedback.reduce(
    (acc, curr) => {
      const found = acc.find((i) => i.rating === curr.rating);
      if (found) {
        found.count += 1;
      }
      return acc;
    },
    [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 0 },
      { rating: 5, count: 0 },
    ]
  );

  function formatYAxis(value: 1 | 2 | 3 | 4 | 5) {
    return `${value} stars`;
  }

  return (
    <>
      <Head>
        <title>Feedback Results</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <header className={styles.header}>
          <h1>Feedback Results</h1>
          <TextLink arrowDirection="left" href="/" label="Go back" />
        </header>
        <h2 className={styles.graphTitle}>Rating distribution</h2>
        <div className={styles.graphWrapper}>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart width={730} height={250} data={ratingDistribution}>
              <XAxis dataKey="rating" tickFormatter={formatYAxis} />
              <YAxis
                dataKey="count"
                stroke="var(--ui-color-near-black)"
                interval={3}
              />
              <Bar dataKey="count" fill="var(--ui-color-blue)" />
            </BarChart>
          </ResponsiveContainer>
        </div>
        <LazyLoadedLatestComments comments={feedback} />
      </Page>
    </>
  );
}
