import { Bar, BarChart, ResponsiveContainer, XAxis, YAxis } from "recharts";
import { Comment, LatestComments } from "components/LatestComments";

import Head from "next/head";
import { Page } from "components/Page";
import { TextLink } from "components/TextLink";
import styles from "../styles/Submitted.module.scss";
import { useLocalStorage } from "hooks/useLocalStorage";

const dummyComments: Comment[] = [
  {
    fullName: "Bob Smith",
    email: "bob.smith@company.com",
    text: "This is great!",
    rating: 5,
    id: Math.floor((1 + Math.random()) * 0x10000).toString(16),
  },
  {
    fullName: "Joe Bloggs",
    email: "joe@gmail.com",
    rating: 3,
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras semper ultricies nulla ac maximus. Integer sollicitudin feugiat est, sodales venenatis lorem tincidunt et. Nulla rutrum quam eget quam sagittis elementum. Aenean vel nisi ac orci tristique placerat. Morbi commodo mauris eu dignissim hendrerit. Duis ornare odio et lacinia lacinia. Maecenas nec gravida metus.",
    id: Math.floor((1 + Math.random()) * 0x10000).toString(16),
  },
];

export default function Submitted() {
  const [feedback] = useLocalStorage<Comment[]>("feedback", dummyComments);

  console.log({ feedback });

  const data = feedback.reduce(
    (acc, curr) => {
      const found = acc.find((i) => i.rating === curr.rating);
      console.log(curr);
      if (found) {
        console.log({ found });
        found.count += 1;
      }
      return acc;
    },
    [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 0 },
      { rating: 5, count: 0 },
    ]
  );

  return (
    <>
      <Head>
        <title>Feedback Results</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <header className={styles.header}>
          <h1>Feedback Results</h1>
          <TextLink arrowDirection="left" href="/" label="Go back" />
        </header>
        <div className={styles.graphWrapper}>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart width={730} height={250} data={data}>
              <XAxis dataKey="rating" />
              <YAxis
                dataKey="count"
                stroke="var(--ui-color-near-black)"
                interval={3}
              />
              <Bar dataKey="count" fill="var(--ui-color-blue)" />
            </BarChart>
          </ResponsiveContainer>
        </div>
        <LatestComments comments={feedback} />
      </Page>
    </>
  );
}
